import Navbar from "@/components/Global/Navbar/Navbar";
import Features from "@/components/Home/Features/Features";
import Frequently from "@/components/Home/Frequently/Frequently";
import Hero from "@/components/Home/Hero/Hero";
import HowWeWork from "@/components/Home/HowWeWork/HowWeWork";
import OurBlog from "@/components/Home/OurBlog/OurBlog";
import ViewPojects from "@/components/Home/ViewPojects/ViewPojects";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Finsweet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Hero />
        <HowWeWork />
        <ViewPojects />
        <Features />
        <OurBlog />
        <Frequently />
      </main>
    </>
  );
}
